### PR TITLE
PackageInfo.g: update Status

### PR DESCRIPTION
**Pull request by fingolfin**
This package is at the very least "deposited". I don't know if you also submitted it for refereeing by the GAP Council; if so, and if it was "accepted" then of course that should be also reflected in the status.

### CODE REVIEW

**Review by kaashif — APPROVED** [review]
Pretty sure this is just deposited and not "accepted" or even "submitted", I don't remember any refereeing happening with this package.

**Comment by kaashif** [comment]
Thanks for the correction!

**Comment by fingolfin** [comment]
Thank you very much. Could you perhaps also make a new release with this? I know that's only a trivial change compared to the previous release, but it'd allow me to fully check of `RepnDecomp` in our TODO list... :-)

**Comment by kaashif** [comment]
Done!

**Pull request merged**
